# Ayu Light theme
set -g status-style "bg=#F3F4F5,fg=#5C6166"
set -g status-left "#[bg=#FFAA33,fg=#FAFAFA,bold] #S #[bg=#F3F4F5,fg=#FFAA33,nobold]  "
set -g status-right "#[fg=#8A9199] %H:%M  %d %b "
set -g status-left-length 40
set -g status-right-length 60
set -g window-status-style "bg=#F3F4F5,fg=#8A9199"
set -g window-status-current-style "bg=#FFAA33,fg=#FAFAFA,bold"
set -g window-status-format "#[bg=#F3F4F5,fg=#8A9199] #I #W "
set -g window-status-current-format "#[bg=#FFAA33,fg=#FAFAFA,bold] #I #W "
set -g window-status-separator ""
set -g pane-border-style "fg=#D2D5D8"
set -g pane-active-border-style "fg=#FFAA33"
set -g message-style "bg=#FFAA33,fg=#FAFAFA"
set -g message-command-style "bg=#D3E1F5,fg=#5C6166"
set -g mode-style "bg=#D3E1F5,fg=#575F66"
set -g copy-mode-selection-style "bg=#D3E1F5,fg=#575F66"
set -g menu-style "bg=#F3F4F5,fg=#5C6166"
set -g menu-selected-style "bg=#FFAA33,fg=#FAFAFA"
set -g popup-style "bg=#F3F4F5,fg=#5C6166"
set -g popup-border-style "fg=#D2D5D8"
